apiVersion: v1
kind: Service
metadata:
  name: svc-goldi
  namespace: ns-goldi
  labels:
    app: svc-goldi
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: goldilocks
  ports:
    - port: 22581
      targetPort: 22581

