apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-goldi
  labels: 
    namespace: ns-goldi
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  
  hostPath:
    path: "/root/k8s/Volume"
