apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-goldi
  namespace: ns-goldi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeName: pv-goldi
